let brands = [
    { id: 1, image: 'Samsung.jpg', name: "Samsung" },
    { id: 2, image: 'Xiaomi.png', name: "Xiaomi" },
    { id: 3, image: 'Apple.png', name: "Apple" },
    { id: 4, image: 'HP.png', name: "HP" },
    { id: 5, image: 'Bosch.jpg', name: "Bosch" },
    { id: 6, image: 'Sony.png', name: "Sony" },
    { id: 7, image: 'Microsoft.png', name: "Microsoft" },
    { id: 8, image: 'Lenovo.png', name: "Lenovo" },
    { id: 9, image: 'Oppo.jpg', name: "Oppo" },
    { id: 10, image: 'Asus.jpg', name: "Asus" }
]

let products = [
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21",
        price: 999,
        image: "Galaxy S21.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (1768 x 2208) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE',
            'степень защиты: IP68',
            'вес: 171 г'
        ]
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21 5G",
        price: 1199,
        image: "Galaxy S21 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.7" (1080 x 2400 ) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 256 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4800 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE , 5G',
            'степень защиты: IP68',
            'вес: 2b00 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy Z Fold 2",
        price: 1199,
        image: "Samsung Galaxy Z Fold 2.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 7.6" (1768 x 2208) 120 Гц',
            'оперативная память: 12 ГБ', 'память: 256 ГБ',
            '3 камеры: 12 МП, 12 МП, 12 МП',
            'аккумулятор: 4500 мА·ч',
            'процессор: Qualcomm Snapdragon 865 Plus ',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 10',
            'беспроводные интерфейсы: NFC, Wi-Fi-6, Bluetooth 5.1',
            'интернет: 4G LTE , 5G',
            'степень защиты: IP68',
            'вес: 279  г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S20 ultra",
        price: 899,
        image: "Galaxy S20 ultra.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.9" (1440 x 3200) 120 Гц',
            'оперативная память: 12 ГБ', 'память: 256 ГБ',
            '3 камеры: 108 МП , 48 МП , 12 МП , 0.3 МП',
            'аккумулятор: 5000 мА·ч',
            'процессор: Samsung Exynos 9 Octa 990',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 10',
            'беспроводные интерфейсы: NFC, Wi-Fi-6, Bluetooth 5.1',
            'интернет: 4G LTE ',
            'степень защиты: IP68',
            'вес: 	220 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy A52",
        price: 629,
        image: "Samsung Galaxy A52.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (2400x1080) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 171 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21 Ultra 5G",
        price: 1000,
        image: "Galaxy S21 Ultra 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.8" (3200x1440) 120 Гц',
            'оперативная память: 12 ГБ',
            'память: 128 ГБ, 256 ГБ',
            ' 4 камеры: 108 МП, 12 МП, 10 МП, 10 МП',
            'аккумулятор: 5000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.2',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 228 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi MI11 5G",
        price: 840,
        image: "Xiaomi MI11 5G.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.81" (3200x1440) 120 Гц',
            'оперативная память: 8 ГБ',
            'память: 256 ГБ',
            '3 камеры: 108 МП, 13 МП, 5 МП',
            'аккумулятор: 4600 мА·ч',
            'процессор: Qualcomm Snapdragon 888',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.2',
            ' интернет: 4G LTE, 5G',
            'вес: 196 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi MI11 Ultra 5G",
        price: 1399,
        image: "Xiaomi MI11 Ultra 5G.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.81 ", изогнутый, 3200х1440 (20:9), 120 Гц, 515 ppi',
            'Память:256 ГБ, ОЗУ 12 ГБ',
            'Процессор:8 ядер(а), 2.84 ГГц',
            'Камера:3 модуля',
            'Видео:fullHD 60 fps, ultraHD 4K 60fps, стабилизация',
            'Емкость батареи:5000 мАч',
            'Вес:234г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21+",
        price: 1099,
        image: "Galaxy S21 plus.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.7" (1080 x 2400) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4800 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE',
            'степень защиты: IP68',
            'вес: 200 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Iphone 12 Pro Max",
        price: 1299,
        image: "iPhone 12 Pro Max.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.7" (2778x1284) 60 Гц',
            'оперативная память: 6 ГБ',
            'память: 512 ГБ',
            '3 камеры: 12 МП, 12 МП, 12 МП',
            'аккумулятор: 3867 мА·ч',
            'процессор: Apple A14 Bionic',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: iOS 14',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 226 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPad Pro 11",
        price: 1299,
        image: "Apple iPad Pro 11.png",
        liked: false,
        cart: 0,
        description: [
            'диагональ: 11" (2388x1668) IPS',
            'встроенная память: 2048 ГБ',
            'оперативная память: 16 ГБ',
            'процессор: Apple M1',
            'операционная система: iPadOS',
            'камеры: основная 12 МП, 10 МП, фронтальная 7 МП',
            'SIM-карты: отсутствует',
            'динамики: стерео',
            'беспроводные интерфейсы: WiFi 802.11ax, Bluetooth 5.0',
            'проводные интерфейсы: USB-C',
            'время работы: 10 ч (28.65 Вт·ч)',
            'размеры: 247.6x178.5x5.9 мм, вес: 466 г',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S20 Ultra 5G",
        price: 1299,
        image: "Galaxy S20 ultra 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (2400x1080) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 171 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Redmi Note 10 Pro",
        price: 500,
        image: "Redmi Note 10 Pro.png",
        liked: false,
        cart: 0,
        description: [
            'SoC Qualcomm Snapdragon 730G, 8 ядер (2×Kryo 470 Gold @2,2 ГГц + 6×Kryo 470 Silver @1,8 ГГц)',
            'GPU Adreno 618.',
            'Операционная система Android 9.0 (Pie); MIUI 11',
            'Сенсорный дисплей AMOLED 6,47″, 2340×1080, 19,5:9, 398 ppi',
            'Оперативная память (RAM) 8 ГБ, внутренняя память 256 ГБ'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony Xperia",
        price: 670,
        image: "Sony Xperia.png",
        liked: false,
        cart: 0,
        description: [
            'Габариты :166 х 72 х 7,9 мм',
            'Масса:181 г',
            'Размер дисплея:6,5-дюймовый дисплей CinemaWide™ с соотношением сторон 21:9',
            'Разрешение дисплея:4K HDR OLED (3840 x 1644)',
            'Камера:Тройная камера'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone 7 ",
        price: 200,
        image: "Apple Iphone 7.png",
        liked: false,
        cart: 0,
        description: [
            'SoC Apple A10 Fusion (4 ядра, 2 из которых работают на частоте 2,34 ГГц, 64-битная архитектура ARMv8-A)',
            'GPU Apple A10 Fusion',
            'Сопроцессор движения Apple M10, включающий барометр, акселерометр, гироскоп и компас',
            'RAM 2 ГБ',
            'Флэш-память 32/64/128/256 ГБ',
            'Поддержка карт памяти отсутствует'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy S10",
        price: 350,
        image: "Samsung Galaxy S10.webp",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6,1 дюйма',
            'Разрешение экрана: QHD+',
            'Память: 8/128 Гбайт',
            'Основная камера: 16 + 12 + 12 Мп',
            'Фронтальная камера: 10 Мп',
            'Емкость аккумулятора: 3400 мАч'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP 440",
        price: 630,
        image: "HP 440.png",
        liked: false,
        cart: 0,
        description: [
            'Intel Core i7-7500U 2 x 2.7 - 3.5 GHz, Kaby Lake.',
            'NVIDIA GeForce 930MX - 2048 Мбайт, Ядро: 952 МГц, Память: 1000 МГц, DDR3',
            'ForceWare 368.71, Optimus',
            'ОЗУ:8192 Мбайт , DDR4-2133, одноканальная, один из двух слотов доступен для расширения до максимум 16 Гб',
            'Материнская плата:Intel Kaby Lake-U Premium PCH',
            'Вес : 1.702 Кг, адаптер питания: 362 г'
        ]
    },
   
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface 3 Pro",
        price: 1000,
        image: "Microsoft Surface Pro 3.webp",
        liked: false,
        cart: 0,
        description: [
            'Процессор:	Core i3-4020Y Core i5-4300U Core i7-4650U',
            'Оперативная память DDR3-1600	4/8 ГБ',
            'Экран	12 дюймов (2160×1440)',
            'Объем SSD-накопителя	64/128/256/512 ГБ',
            'Операционная система	Windows 8.1 Pro (64-битная)',
            'Масса без блока питания	800 г',
            'Аккумулятор	Литий-ионный, 42 Вт·ч'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface 7",
        price: 1400,
        image: "MS Surface 7.webp",
        liked: false,
        cart: 0,
        description: [
            'Процессор: Intel Core i5-1035G4 1,1 ГГц (4-ядерный, кэш 6 Мб, до 3,7 ГГц);',
            'Графика: Intel Iris Plus Graphics',
            'Оперативная память: 8 Гб DDR4x',
            'Экран: 12,3-дюймовый PixelSense (2736 x 1824), 1500:1, 100% sRGB, 3:2',
            'Физическая память: 256 Гб SSD',
            'Подключения: Wi-Fi 6 802.11ax (2 x 2 MIMO), Bluetooth 5',
            'Вес: 771 г'
        ]
    }, 
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP-spectre-x360",
        price: 700,
        image: "HP-spectre-x360.png",
        liked: false,
        cart: 0,
        description: [
            'Процессор: Intel® Core™ i5-8265U (1.8 ГГц, до 3.9 ГГц, 6 МБ кэш L3, 4 ядра)',
            'Оперативная память: 8192 МБ, DDR4, 2400 МГц',
            'Жёсткий диск: 256 ГБ PCIe® NVMe™ M.2 SSD (максимум до 2 ТБ PCIe® NVMe™ M.2 SSD)',
            'Графика: Intel® UHD Graphics 620',
            'Операционная система: Windows® 10 (64-разрядная)',
            'Звук: стереодинамики Bang & Olufsen',
            'Cвязь: Wi-Fi 802.11b/g/n/ac (2x2), Bluetooth 5.0',
            'Размеры: 308.8 х 217.9 х 14.7 мм, вес 1.33 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch Холодильник",
        price: 1130,
        image: "Bosch fridge.webp",
        liked: false,
        cart: 0,
        description: [
            'Тип: холодильник с морозильником',
            'Управление: электромеханическое',
            'Цветовая группа: серебристый',
            'Автономное сохранение холода:до 22 ч',
            'Мощность замораживания: до 4.5 кг/cутки',
            'Общий объем:318 л',
            'Количество камер:2'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch плита",
        price: 320,
        image: "Bosch oven.webp",
        liked: false,
        cart: 0,
        description: [
            'Материал корпуса:пластик',
            'Максимальная мощность:750 Вт',
            'Размеры (Ш*В*Г):5.8x39x5.7 см',
            'Вес:1.96 кг'

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch Холодильник",
        price: 750,
        image: "Bosch refrigerator.webp",
        liked: false,
        cart: 0,
        description: [
            'Тип: холодильник с морозильником',
            'Управление: электромеханическое',
            'Цветовая группа: серебристый',
            'Автономное сохранение холода:до 22 ч',
            'Мощность замораживания: до 4.5 кг/cутки',
            'Общий объем:318 л',
            'Количество камер:2'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony TV",
        price: 250,
        image: "Sony TV.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6,1 дюйма',
            'Разрешение экрана: QHD+',
            'Память: 8/128 Гбайт',
            'Основная камера: 16 + 12 + 12 Мп',
            'Фронтальная камера: 10 Мп',
            'Емкость аккумулятора: 3400 мАч'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: " MacBook Pro 16” ",
        price: 2399,
        image: "MacBook Pro 16.png",
        liked: false,
        cart: 0,
        description: [
            'Разрешение экрана: 3072x1920',
            'Тип видеокарты: встроенная, дискретная, дискретная и встроенная',
            'Видеокарта: AMD Radeon Pro 5300M, AMD Radeon Pro 5500M',
            'Конфигурация накопителей: SSD',
            'Операционная система: macOS',
            'Экран: 16 дюймов, 3072x1920, широкоформатный',
            'Тип матрицы экрана:IPS',
            'Подсветка экрана: светодиодная',
            'Объем видеопамяти 4 ГБ',
            'Тип видеопамяти: GDDR6',
            'Общий объем накопителей: 1024 ГБ',
            'Общий объем накопителей SSD: 1024 ГБ',
            'Оптический привод: нет',
            'Тип аккумулятора: Li-Pol',
            'Устройства позиционирования: Touchpad',
            'Количество клавиш клавиатуры: 66',
            'Встроенный микрофон: есть',
            'Веб-камера:есть, 1 МП',
            'Сканер отпечатка пальца: есть',
            'Особенности: металлический корпус',
            'Размеры (ДхШхТ): 357.9x245.9x16.2 мм',
            'Вес:2 кг',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Elite Folio 13.5",
        price: 1786,
        image: "HP Elite Folio 13.5.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 12.5" (2560x1440)',
            'процессор: Intel Core M 5Y71 (2x1200 МГц)',
            'оперативная память: 8 ГБ LPDDR3 1600 МГц',
            'накопитель: SSD 512 ГБ',
            'встроенная видеокарта: Intel HD Graphics 5300',
            'разъемы: USB 3.0 Type A x 2, выход HDMI, интерфейс док-станции, микрофон/наушники Combo',
            'беспроводная связь: Wi-Fi 802.11n, Bluetooth 4.0',
            'операционная система: Windows 10 Pro',
            'pазмеры: 310x210x15.7 мм',
            'Ядро процессора: Broadwell',
            'Количество ядер процессора: 2',
            'Экран: 12.5 дюймов, 2560x1440, широкоформатный, сенсорный, мультитач',
            'Подсветка экрана: светодиодная',
            'Тип видеокарты: встроенная',
            'вес: 1.21 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: " Bosch холодильник 2х-камерный ",
        price: 1405,
        image: "Bosch bigfridge.webp",
        liked: false,
        cart: 0,
        description: [
            'Морозильная камера: Side by Side (сбоку)',
            'Цвет / Материал покрытия: серебристый / пластик/металл',
            'Управление: электронное',
            'Энергопотребление: класс A++ (363 кВтч/год)',
            'Количество компрессоров: 1',
            'Количество камер: 2',
            'Общий объем: 560 л',
            'Объем холодильной камеры :371 л',
            'Объем морозильной камеры: 181 л',
            'Дисплей: есть',
            'Генератор льда: в комплекте',
            'Материал полок: стекло', 'Уровень шума:до 42 дБ',
            'Климатический класс: N, SN, ST, T',
            'Срок службы: 60 мес.',
            'Гарантийный срок: 12 мес.'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: " OPPO Find X3 Pro 12/256GB ",
        price: 675,
        image: "OPPO Find X3 Pro 12.png",
        liked: false,
        cart: 0,
        description: [
            'Версия ОС на начало продаж: Android 11',
            'Количество SIM-карт: 2',
            'Вес: 193 г',
            'Размеры (ШxВxТ): 74x163.6x8.26 мм',
            'Тип экрана:цветной AMOLED, сенсорный',
            'Диагональ:6.7 дюйм.',
            'Размер изображения: 3216x1440',
            'Число пикселей на дюйм (PPI): 526',
            'Геопозиционирование: BeiDou, A-GPS, Galileo, ГЛОНАСС, GPS',
            'Процессор: Qualcomm Snapdragon 888, 2842 МГц',
            'Количество ядер процессора: 8',
            'Видеопроцессор: Adreno 660',
            'Объем встроенной памяти: 256 ГБ',
            'Объем оперативной памяти: 12 ГБ',
            'Комплектация: кабель USB type-C, зарядное устройство, инструмент для извлечения SIM-карты, чехол, наушники, руководство пользователя',
            'Особенности: Gorilla Glass 5',
            'Дата анонсирования: 2021-03-11'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo Legion Y740-17",
        price: 2450,
        image: "Lenovo Legion Y740-17.webp",
        liked: false,
        cart: 0,
        description: [
            'Разрешение экрана: 1920x1080',
            'Тип видеокарты: дискретная и встроенная',
            'Видеокарта: NVIDIA GeForce RTX 2080 MAX-Q',
            'Конфигурация накопителей: SSD',
            'Операционная система:Windows 10 Home',
            'Тип: игровой ноутбук',
            'экран: 17.3" (1920x1080)',
            'матрица: IPS, 144 Гц',
            'процессор: Intel Core i7 8750H (6x2200 МГц)',
            'оперативная память: 16 ГБ DDR4 2666 МГц',
            'накопитель: SSD 512 ГБ',
            'pазмеры: 412x305x25.45 мм',
            'вес: 2.9 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "OPPO A5 4/32GB",
        price: 245,
        image: "Oppo A5.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (1520×720)',
            'оперативная память: 4 ГБ',
            'память: 32 ГБ, слот для карты памяти',
            'двойная камера: 13 МП, 2 МП',
            'аккумулятор: 4230 мА·ч',
            'процессор: Qualcomm Snapdragon 450',
            'SIM - карты: 2(nano SIM)',
            'операционная система: Android 8.1',
            'беспроводные интерфейсы: Wi - Fi, Bluetooth 4.2',
            'интернет: 4G LTE',
            'вес: 170 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo ThinkPad X1 Extreme",
        price: 1670,
        image: "Lenovo ThinkPad X1 Extreme.webp",
        liked: false,
        cart: 0,
        description: [
            'Операционная система: Windows 10 Pro',
            'Процессор: Intel Core i7 9750H',
            'Частота процессора: 2600 МГц',
            'Ядро процессора: Coffee Lake',
            'Количество ядер процессора: 6',
            'Диагональ экрана: 15.6" ',
            'Разрешение экрана: 3840x2160',
            'Широкоформатный экран: есть',
            'Тип покрытия экрана: антибликовый',
            'Тип матрицы экрана: IPS',
            'Светодиодная подсветка экрана: есть',
            'Тип видеокарты: дискретная и встроенная',
            'Производитель видеопроцессора: NVIDIA',
            'Видеокарта: NVIDIA GeForce GTX 1650',
            'Тип видеопамяти: GDDR5 '
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo IdeaPad Slim 7",
        price: 919,
        image: 'Lenovo IdeaPad Slim 7.webp',
        liked: false,
        cart: 0,
        description: [
            'Процессор: Intel Core i7 1065G7 1300 МГц',
            'Ядро процессора: Ice Lake',
            'Количество ядер процессора: 4',
            'Объем кэша L3: 8 МБ',
            'Чипсет: Intel SoC',
            'Экран : 14 дюймов, 3840x2160, широкоформатный',
            'Тип покрытия экрана: глянцевый',
            'Тип матрицы экрана: IPS',
            'Подсветка экрана: светодиодная',
            'Тип видеокарты: встроенная',
            'Видеопроцессор: Intel Iris Plus Graphics',
            'Тип видеопамяти: SMA',
            'Веб-камера: есть, 0.92 МП',
            'Особенности: металлический корпус',
            'Размеры: 320.6x208.18x14.9 мм',
            'Вес: 1.54 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony OLED KD-55A8",
        price: 1867,
        image: 'Sony OLED Sony KD-55A8.png',
        liked: false,
        cart: 0,
        description: [
            'разрешение: 4K UHD (3840x2160), HDR',
            'диагональ экрана: 54.6"',
            'частота обновления экрана: 50 Гц',
            'формат HDR: HDR10, Dolby Vision',
            'мощность звука: 30 Вт (2х10 + 2х5 Вт)',
            'платформа Smart TV: Android',
            'беспроводные интерфейсы: Wi-Fi 802.11ac, 802.11b, 802.11g, 802.11n, Bluetooth',
            'проводные интерфейсы: HDMI 2.1 x 4, USB x 3, Ethernet, выход аудио оптический, выход на наушники',
            'крепление VESA: 300×300 мм',
            'размеры без подставки (ШxВxГ): 1227x712x52 мм',
            'размеры с подставкой (ШxВxГ): 1227x733x326 мм',
            'вес: 18.6 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi Poco X3 Pro 8/256GB",
        price: 320,
        image: 'Xiaomi Poco X3 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'экран: 6.67" (2400x1080) 120 Гц',
            'оперативная память: 8 ГБ',
            'память: 256 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 8 МП, 2 МП, 2 МП',
            'аккумулятор: 5160 мА·ч',
            'процессор: Qualcomm Snapdragon 860',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'степень защиты: IP53',
            'вес: 215 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "Oppo Reno 4 Pro 5G 256GB 12GB",
        price: 505,
        image: 'OPPO Reno 4 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'экран: 6.5" (2400x1080)',
            'оперативная память: 12 ГБ',
            'память: 256 ГБ',
            '3 камеры: 48 МП, 12 МП, 13 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Qualcomm Snapdragon 765G 5G',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 10',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE',
            'вес: 172 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Iphone 11",
        price: 895,
        image: 'Iphone 11.png',
        liked: false,
        cart: 0,
        description: [
            'Версия ОС на начало продаж: iOS 13',
            'Тип корпуса: классический',
            'Материал корпуса: металл и стекло',
            'Конструкция: влагозащита',
            'Степень защиты: IP68',
            'Количество SIM-карт: 2',
            'Тип SIM-карты: nano SIM+eSIM',
            'Бесконтактная оплата: есть',
            'Основные (тыловые) камеры: 12 МП 2x F/2.40, 12 МП F/1.80',
            'Функции основной (тыловой) фотокамеры: автофокус, оптическая стабилизация, режим макросъемки, оптический Zoom 2x',
            'Фотовспышка: тыльная, светодиодная',
            'Запись видеороликов: есть (HEVC, H.264)',
            'Макс. разрешение видео: 3840x2160',
            'Geo Tagging: есть',
            'Фронтальная камера: есть, 12 МП',
            'Вес: 194 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy Tab S7 plus",
        price: 825,
        image: 'Galaxy Tab S7+.png',
        liked: false,
        cart: 0,
        description: [
            'Операционная система на начало продаж: Android 10',
            'Процессор: Qualcomm Snapdragon 865+ 3100 МГц',
            'Частота процессора: 3100 МГц',
            'Количество ядер: 8',
            'Вычислительное ядро: Kryo',
            'Техпроцесс: 7 нм',
            'Объем встроенной память: 128 ГБ',
            'Оперативная память: 6 ГБ LPDDR4',
            'Слот для карт памяти: есть, microSDXC, до 1024 ГБ',
            'Экран: 12.4", 2800x1752',
            'Тип экрана: Super AMOLED, глянцевый',
            'Сенсорный экран: емкостный, мультитач',
            'Число пикселей на дюйм (PPI): 266',
            'Видеопроцессор: Adreno 650',
            'Количество основных (тыловых) камер:2',
            'Разрешения основных (тыловых) камер: 13 МП, 5 МП',
            'Особенности камеры: вспышка, автофокус',
            'Фронтальная камера: есть, 8 МП',
            'Размеры: 285x185x5.7 мм',
            'Вес: 575 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Elite Dragonfly G2 Notebook PC",
        price: 1959,
        image: 'HP Elite Dragonfly G2 Notebook PC.png',
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (3840x2160)',
            'матрица: IPS, 60 Гц',
            'процессор: Intel Core i7 1165G7 (4x2800 МГц)',
            'оперативная память: 32 ГБ LPDDR4X 4266 МГц',
            'накопитель: SSD 1 ТБ',
            'встроенная видеокарта: Intel Iris Xe Graphics',
            'разъемы: USB 3.1 Type A, выход HDMI, микрофон/наушники Combo, Thunderbolt/USB 4 x 2',
            'фунционал USB Type-C: Thunderbolt 4',
            'беспроводная связь: Wi-Fi 802.11ax, Bluetooth 5.0',
            'емкость аккумулятора: 56 Вт⋅ч',
            'операционная система: Windows 10 Pro',
            'pазмеры: 304.3x197.5x16.1 мм',
            'вес: 0.99 кг'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Xperia 1 II - 6.5” 4K HDR",
        price: 1959,
        image: 'Xperia 1 II - 6.5” 4K HDR.png',
        liked: false,
        cart: 0,
        description: [
            'экран: 6.5" (3840x1644)',
            'оперативная память: 6 ГБ',
            'память: 128 ГБ, слот для карты памяти',
            '3 камеры: 12 МП, 12 МП, 12 МП',
            'аккумулятор: 3330 мА·ч',
            'процессор: Qualcomm Snapdragon 855',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 9.0',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LT',
            'Основные (тыловые) камеры: 12 МП 2x F/1.60, 12 МП F/2.40, 12 МП F/2.40',
            'Фронтальная камера: есть, 8 МП',
            'Число пикселей на дюйм (PPI): 643'

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus Zenfone 8",
        price: 785,
        image: 'Asus Zenfone 8.png',
        liked: false,
        cart: 0,
        description: [
            'Версия ОС на начало продаж: Android 11',
            'Тип корпуса: классический',
            'Конструкция: влагозащита',
            'Степень защиты: IP68',
            'Количество SIM-карт: 2',
            'Тип SIM-карты: nano SIM',
            'Тип экрана: цветной AMOLED, сенсорный',
            'Размеры: 68.5x148x8.9 мм',
            'Диагональ: 5.9 дюйм.',
            'Размер изображения: 2400x1080',
            'Число пикселей на дюйм (PPI): 446',
            'Соотношение сторон: 20:9',
            'Процессор: Qualcomm Snapdragon 888, 2840 МГц',
            'Количество ядер процессора: 8',
            'Видеопроцессор: Adreno 660',
            'Объем встроенной памяти: 256 ГБ',
            'Объем оперативной памяти: 16 ГБ',
            'Вес: 169 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface Pro X",
        price: 1170,
        image: 'MS Surface Pro X.webp',
        liked: false,
        cart: 0,
        description: [
            'диагональ: 13" (2880x1920)',
            'встроенная память: 128 ГБ',
            'оперативная память: 8 ГБ',
            'процессор: Microsoft SQ1',
            'операционная система: Windows 10',
            'камеры: основная 10 МП, фронтальная 5 МП',
            'SIM-карты: 1 (nano SIM)',
            'динамики: стерео',
            'беспроводные интерфейсы: 4G LTE, WiFi 802.11ac, Bluetooth 5.0',
            'проводные интерфейсы: USB-C',
            'время работы: 13 ч',
            'размеры: 287x208x7.3 мм, вес: 774 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo ThinkPad X1 Carbon Gen 9",
        price: 1959,
        image: 'ThinkPad X1 Carbon Gen 9.webp',
        liked: false,
        cart: 0,
        description: [
            'Размер экрана: 14"-14.9"',
            'Операционная система: Windows 10 Pro',
            'Разрешение экрана: 1920x1080',
            'Сенсорный экран: да',
            'Линейка процессора: Intel Core i5, Intel Core i7',
            'сетевая карта:: WLAN/Modem',
            'Беспроводная связь: Wi-Fi IEEE 802.11ax, Bluetooth 5.0',
            'Интерфейсы: USB 3.1 Type A x 2, выход HDMI, Thunderbolt 3 x 2, микрофон/наушники Combo',
            'Фунционал USB Type-C: Thunderbolt 3',
            'Веб-камера: есть, 0.92 МП',
            'Сканер отпечатка пальца: есть',
            'Особенности: металлический корпус, слот замка безопасности',
            'Дополнительная информация: Ethernet подключается через адаптер'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "OPPO A94",
        price: 757,
        image: 'OPPO A94.png',
        liked: false,
        cart: 0,
        description: [
            'экран: 6.43" (2400x1080) 60 Гц',
            'оперативная память: 4 ГБ',
            'память: 128 ГБ, слот для карты памяти',
            '3 камеры: 48 МП, 2 МП, 2 МП',
            'аккумулятор: 5000 мА·ч',
            'процессор: Qualcomm Snapdragon 662',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'вес: 175 г'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus ZenBook-15-UX533",
        price: 1336,
        image: 'Asus ZenBook-15-UX533.png',
        liked: false,
        cart: 0,
        description: [
            'Размер экрана:15"-15.9"',
            'Разрешение экрана:1920x1080',
            'Сенсорный экран:нет',
            'Линейка процессора:Intel Core i5',
            'модель 90NB0NK5-M05600',
            'Экран: 15.6 дюймов, 1920x1080, широкоформатный',
            'Операционная система: Windows 10 Home',
            'Тип покрытия экрана: матовый',
            'Тип матрицы экрана: IPS',
            'Частота обновления экрана: 60 Гц',
            'Подсветка экрана: светодиодная',
            'Тип видеокарты: дискретная и встроенная',
            'Видеопроцессор: NVIDIA GeForce GTX 1650 MAX-Q',
            'Объем видеопамяти: 4 ГБ',
            'Тип видеопамяти: GDDR5',
            'Вес: 1.65 кг'
        ]
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus ROG Phone 5 Pro",
        price: 1308,
        image: 'Asus ROG Phone 5 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'Версия ОС на начало продаж: Android 11',
            'Материал корпуса: алюминий и стекло',
            'Количество SIM-карт: 2',
            'Бесконтактная оплата: есть',
            'Размеры: 77.3x172.8x10.3 мм',
            'Тип экрана: цветной AMOLED, сенсорный',
            'Диагональ: 6.78 дюйм.',
            'Размер изображения: 2448x1080',
            'Число пикселей на дюйм (PPI): 395',
            'Процессор: Qualcomm Snapdragon 888',
            'Количество ядер процессора: 8',
            'Видеопроцессор: Adreno 660',
            'Объем встроенной памяти: 256 ГБ',
            'Объем оперативной памяти: 16 ГБ',
            'Количество основных (тыловых) камер: 3',
            'Основные (тыловые) камеры: широкоугольная 64 МП F/1.80, сверхширокоугольная 13 МП F/2.40, макро 5 МП F/2',
            'Функции основной (тыловой) фотокамеры: автофокус, оптическая стабилизация',
            'Фотовспышка: тыльная',
            'Вес: 238 г'
        ]
    }
]

export { brands, products }





