let brands = [
    { id: 1, image: 'Samsung.jpg', name: "Samsung" },
    { id: 2, image: 'xiaomi.png', name: "xiaomi" },
    { id: 3, image: 'Apple.png', name: "Apple" },
    { id: 4, image: 'HP.png', name: "HP" },
    { id: 5, image: 'Bosch.jpg', name: "Bosch" },
    { id: 6, image: 'Sony.png', name: "Sony" },
    { id: 7, image: 'Microsoft.png', name: "Microsoft" },
    { id: 8, image: 'Lenovo.png', name: "Lenovo" },
    { id: 9, image: 'Oppo.jpg', name: "Oppo" },
    { id: 10, image: 'Asus.jpg', name: "Asus" }
]

let products = [{
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21",
        price: 999,
        image: "Galaxy S21.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.2" (1768 x 2208) 120 GH',
            'RAM: 8 GB', 'Storage: 128 GB',
            '3 cameras: 64 Mp, 12 Mp, 12 Mp',
            'Battery: 4000 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wireless interface: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE',
            'Security Level: IP68',
            'Weight: 171 g'
        ]
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21 5G",
        price: 1199,
        image: "Galaxy S21 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.7" (1080 x 2400 ) 120 Gh',
            'RAM : 8 GB', 'storage: 256 GB',
            '3 cameras: 64 MP, 12 MP, 12 MP',
            'Battery: 4800 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wireless interface: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE , 5G',
            'Security level: IP68',
            'Weight: 500 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy Z Fold 2",
        price: 1199,
        image: "Samsung Galaxy Z Fold 2.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 7.6" (1768 x 2208) 120 Gh',
            'RAM: 12 GB', 'Storage: 256 GB',
            '3 Cameras: 12 MP, 12 MP, 12 MP',
            'Battery: 4500 MA·h',
            'processor: Qualcomm Snapdragon 865 Plus ',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 10',
            'wireless display: NFC, Wi-Fi-6, Bluetooth 5.1',
            'Internet: 4G LTE , 5G',
            'Security level: IP68',
            'Weight: 279  g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S20 ultra",
        price: 899,
        image: "Galaxy S20 ultra.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.9" (1440 x 3200) 120 Gh',
            'RAM: 12 GB', 'Storage: 256 GB',
            '3 Cameras: 108 MP , 48 MP , 12 MP , 0.3 MP',
            'Battery: 5000 MA·h',
            'processor: Samsung Exynos 9 Octa 990',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 10',
            'wireless interface: NFC, Wi-Fi-6, Bluetooth 5.1',
            'Internet: 4G LTE ',
            'Security level: IP68',
            'Weight: 220 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy A52",
        price: 629,
        image: "Samsung Galaxy A52.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.2" (2400x1080) 120 Gh',
            'RAM: 8 GB', 'storage: 128 GB',
            '3 cameras: 64 MP, 12 MP, 12 MP',
            'Battery: 4000 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wireless interface: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE, 5G',
            'Security level: IP68',
            'Weight: 171 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21 Ultra 5G",
        price: 1000,
        image: "Galaxy S21 Ultra 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.8" (3200x1440) 120 Gh',
            'operation system: 12 GB',
            'storage: 128 Gb, 256 Gb',
            '4 cameras: 108 MP, 12 Mp, 10 Mp, 10 Mp',
            'battery: 5000 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wirelese display: NFC, Wi-Fi, Bluetooth 5.2',
            'internet: 4G LTE, 5G',
            'Security level: IP68',
            'weight: 228 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "xiaomi MI11 5G",
        price: 840,
        image: "xiaomi MI11 5G.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.81" (3200x1440) 120 Gh',
            'RAM: 8 GB',
            'Storage: 256 GB',
            '3 cameras: 108 MP, 13 MP, 5 MP',
            'Battery: 4600 MA·h',
            'processor: Qualcomm Snapdragon 888',
            'SIM-cards: 2 (nano SIM)',
            'operation system: Android 11',
            'wireless dispay: NFC, Wi-Fi, Bluetooth 5.2',
            'Internet: 4G LTE, 5G',
            'weight: 196 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "xiaomi MI11 Ultra 5G",
        price: 1399,
        image: "xiaomi MI11 Ultra 5G.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.81 ", 3200x1440 (20:9), 120 Gh, 515 ppi',
            'Storage:256 GB, RAM 12 GB',
            'processor:8 cores, 2.84 ggh',
            'Cameras:3 modules',
            'Video:fullHD 60 fps, ultraHD 4K 60fps, balanced',
            'Battery capacity:5000 MAh',
            'Weight:234g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S21+",
        price: 1099,
        image: "Galaxy S21 plus.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.7" (1080 x 2400) 120 Gh',
            'RAM: 8 GB', 'Storage: 128 GB',
            '3 Cameras: 64 MP, 12 MP, 12 MP',
            'Battery: 4800 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE',
            'Security level: IP68',
            'Weight: 200 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Iphone 12 Pro Max",
        price: 1299,
        image: "iPhone 12 Pro Max.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.7" (2778x1284) 60 Gh',
            'RAM: 6 GB',
            'Storage: 512 GB',
            '3 Cameras: 12 MP, 12 MP, 12 MP',
            'Battery: 3867 MA·h',
            'processor: Apple A14 Bionic',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: iOS 14',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.0',
            'Internet: 4G LTE, 5G',
            'Security level: IP68',
            'Weight: 226 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPad Pro 11",
        price: 1299,
        image: "Apple iPad Pro 11.png",
        liked: false,
        cart: 0,
        description: [
            'diagonal: 11" (2388x1668) IPS',
            'externalStorage: 2048 GB',
            'RAM: 16 GB',
            'processor: Apple M1',
            'operation system: iPadOS',
            'Cameras: main 12 MP, 10 MP, frontal 7 MP',
            'SIM-cards: 2',
            'dynamics: stereo',
            'wireless display: WiFi 802.11ax, Bluetooth 5.0',
            'wired interfaces: USB-C',
            'work time: 10 h (28.65 Wt·h)',
            'Size: 247.6x178.5x5.9 MM, Weight: 466 g',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S20 Ultra 5G",
        price: 1299,
        image: "Galaxy S20 ultra 5G.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.2" (2400x1080) 120 Gh',
            'RAM: 8 GB', 'Storage: 128 GB',
            '3 Cameras: 64 MP, 12 MP, 12 MP',
            'Battery: 4000 MA·h',
            'processor: Samsung Exynos 2100',
            'SIM-cards: 2 (nano SIM+eSIM)',
            'operation system: Android 11',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE, 5G',
            'Security level: IP68',
            'Weight: 171 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Redmi Note 10 Pro",
        price: 500,
        image: "Redmi Note 10 Pro.png",
        liked: false,
        cart: 0,
        description: [
            'SoC Qualcomm Snapdragon 730G, 8 cores (2xKryo 470 Gold @2,2 ggh + 6xKryo 470 Silver @1,8 ggh)',
            'GPU Adreno 618.',
            'operation system Android 9.0 (Pie); MIUI 11',
            'Wireless display AMOLED 6,47″, 2340x1080, 19,5:9, 398 ppi',
            'RAM (RAM) 8 GB, Internal Storage 256 GB'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony xperia",
        price: 670,
        image: "Sony xperia.png",
        liked: false,
        cart: 0,
        description: [
            'size :166 x 72 x 7,9 MM',
            'Weight:181 g',
            'Display size:6,5-inchs display CinemaWide™ with aspect ratio 21:9',
            'Display Size:4K HDR OLED (3840 x 1644)',
            'Cameras:Triple Cameras'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone 7 ",
        price: 200,
        image: "Apple Iphone 7.png",
        liked: false,
        cart: 0,
        description: [
            'SoC Apple A10 Fusion (4 cores, 2 of them are in 2,34 ggh, 64-bit ARMv8-A)',
            'GPU Apple A10 Fusion',
            'coprocessor with Apple M10, includes barometr, axcilemetr, gyroscope и compass',
            'RAM 2 GB',
            'SD 32/64/128/256 GB',
            'memory card support: No'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy S10",
        price: 350,
        image: "Samsung Galaxy S10.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6,1 inches',
            'Screen Size: QHD+',
            'Storage: 8/128 GB',
            'main Cameras: 16 + 12 + 12 MP',
            'frontal Cameras: 10 MP',
            'Battery: 3400 MAh'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP 440",
        price: 630,
        image: "HP 440.png",
        liked: false,
        cart: 0,
        description: [
            'Intel Core i7-7500U 2 x 2.7 - 3.5 GHz, Kaby Lake.',
            'NVIDIA GeForce 930Mx - 2048 MB, Ядро: 952 MGh, Storage: 1000 MGh, DDR3',
            'ForceWare 368.71, Optimus',
            'RAM:8192 MB , DDR4-2133, single channeled, one of the two up to slots available for expansion up to Maximum 16 GB',
            'Motherboard:Intel Kaby Lake-U Premium PCH',
            'Weight : 1.702 kg, power adapter: 362 g'
        ]
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface 3 Pro",
        price: 1000,
        image: "Microsoft Surface Pro 3.webp",
        liked: false,
        cart: 0,
        description: [
            'processor:	Core i3-4020Y Core i5-4300U Core i7-4650U',
            'RAM DDR3-1600	4/8 GB',
            'Screen	12 inchs (2160x1440)',
            'SSD capacity	64/128/256/512 GB',
            'operation system	Windows 8.1 Pro (64-bit)',
            'Weight without power adapter: 800 g',
            'Battery: Li-ion, 42 Wt·h'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface 7",
        price: 1400,
        image: "MS Surface 7.webp",
        liked: false,
        cart: 0,
        description: [
            'processor: Intel Core i5-1035G4 1,1 ggh (4-cores, cache 6 MB, up to 3,7 ggh);',
            'graphics: Intel Iris Plus Graphics',
            'RAM: 8 GB DDR4x',
            'Screen: 12,3-inch PixelSense (2736 x 1824), 1500:1, 100% sRGB, 3:2',
            'Storage: 256 GB SSD',
            'Connection: Wi-Fi 6 802.11ax (2 x 2 MIMO), Bluetooth 5',
            'Weight: 771 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP-spectre-x360",
        price: 700,
        image: "HP-spectre-x360.png",
        liked: false,
        cart: 0,
        description: [
            'processor: Intel® Core™ i5-8265U (1.8 ggh, up to 3.9 ggh, 6 MB cache L3, 4 cores)',
            'RAM: 8192 MB, DDR4, 2400 MGh',
            'Hardware: 256 GB PCIe® NVMe™ M.2 SSD (Maximum up to 2 ТБ PCIe® NVMe™ M.2 SSD)',
            'graphics: Intel® UHD Graphics 620',
            'operation system: Windows® 10 (64-bit)',
            'sound: stereodynamics Bang & Olufsen',
            'Connection: Wi-Fi 802.11b/g/n/ac (2x2), Bluetooth 5.0',
            'Size: 308.8 x 217.9 x 14.7 MM, Weight 1.33 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch refrigerator",
        price: 1130,
        image: "Bosch fridge.webp",
        liked: false,
        cart: 0,
        description: [
            'Type: refrigerator with freeze container',
            'Control: Electro-mechanical',
            'Color: grey-shady',
            'Autonomous cold storage:up to 22 h',
            'Freezing storage: up to 4.5 kg/day',
            'Total Volume: 318 litres',
            'number of cameras:2'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch пlitresитa",
        price: 320,
        image: "Bosch oven.webp",
        liked: false,
        cart: 0,
        description: [
            'corpus type: plastic',
            'maximum power storage:750 Wt',
            'Size:5.8x39x5.7 cm',
            'Weight:1.96 kg'

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch refrigerator",
        price: 750,
        image: "Bosch refrigerator.webp",
        liked: false,
        cart: 0,
        description: [
            'Type: refrigerator with freeze container',
            'Control: Electro-mechanical',
            'Color: grey-shady',
            'Autonomous cold storage: up to 22 h',
            'Freezing power: up to 4.5 kg/day',
            'Total Volume:318 litres',
            'number of cameras:2'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony TV",
        price: 250,
        image: "Sony TV.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6,1 inchesA',
            'Screen Size: QHD+',
            'Storage: 8/128 GB',
            'main Cameras: 16 + 12 + 12 MP',
            'frontal Cameras: 10 MP',
            'power capacity: 3400 MAh'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: " MacBook Pro 16” ",
        price: 2399,
        image: "MacBook Pro 16.png",
        liked: false,
        cart: 0,
        description: [
            'Screen Size: 3072x1920',
            'Videcard type: discrete and built-in,',
            'Videocards: AMD Radeon Pro 5300M, AMD Radeon Pro 5500M',
            'drive configuration: SSD',
            'operation system: macOS',
            'Screen: 16 inchs, 3072x1920, widescreen',
            'Screen Matrix Type:IPS',
            'screen backlight: LED',
            'video memory size 4 GB',
            'Videotype memory: GDDR6',
            'total storage space: 1024 GB',
            'optical drive: not available',
            'Type Batterya: Li-Pol',
            'Positioning devices: Touchpad',
            'number of keypads: 66',
            'built-in microphone: available',
            'Web-Cameras:available, 1 MP',
            'fingerprint availability: available',
            'Characteristics: metal case',
            'Size (WxHxL): 357.9x245.9x16.2 MM',
            'Weight:2 kg',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Elite Folio 13.5",
        price: 1786,
        image: "HP Elite Folio 13.5.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 12.5" (2560x1440)',
            'processor: Intel Core M 5Y71 (2x1200 MGh)',
            'RAM: 8 GB LPDDR3 1600 MGh',
            'storage device: SSD 512 GB',
            'externalVideocards: Intel HD Graphics 5300',
            'adapter: USB 3.0 Type A x 2, HDMI, Microphones/headphones Combo',
            'Wireless connection: Wi-Fi 802.11n, Bluetooth 4.0',
            'operation system: Windows 10 Pro',
            'Size: 310x210x15.7 MM',
            'processor core: Broadwell',
            'number of cores: 2',
            'Screen: 12.5 inchs, 2560x1440, widescreen, sensor, multitouch',
            'screen backlight: LED',
            'Videcard type: External',
            'Weight: 1.21 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: " Bosch two-chamber refrigerator ",
        price: 1405,
        image: "Bosch bigfridge.webp",
        liked: false,
        cart: 0,
        description: [
            'freezer: Side by Side',
            'Color / material cover: grey-shady / plastic/Metalic',
            'Control: electronic',
            'Energy consumption: class A++ (363 кWth/year)',
            'number of compressors: 1',
            'number of cameras: 2',
            'Total Volume: 560 litres',
            'refrigerator compartment volume :371 litres',
            'freezer volume: 181 litres',
            'display: available',
            'generator availability: complected',
            'material coverage: glass', 'Sound level:up to 42 dB',
            'climate class: N, SN, ST, T',
            'life service: 60 mo.',
            'warranty: 12 mo.'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: " OPPO Find x3 Pro 12/256GB ",
        price: 675,
        image: "OPPO Find x3 Pro 12.png",
        liked: false,
        cart: 0,
        description: [
            'OC version at the beginning of sales: Android 11',
            'number of SIM-cards: 2',
            'Weight: 193 g',
            'Size (HxLxW): 74x163.6x8.26 MM',
            'Screen Type:colorful AMOLED, sensor',
            'diagonal:6.7 inches.',
            'image size: 3216x1440',
            'number of pixels in  inches (PPI): 526',
            'geopositioning: BeiDou, A-GPS, Galileo, GLONASS, GPS',
            'processor: Qualcomm Snapdragon 888, 2842 MGh',
            'number of cores: 8',
            'Videoprocessor: Adreno 660',
            'built-in memory: 256 GB',
            'RAM: 12 GB',
            'equipment: USB type-C, charger, sim card eject tool, phone case, headphones, user guide',
            'Characteristics: Gorilla Glass 5',
            'Release date: 2021-03-11'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo Legion Y740-17",
        price: 2450,
        image: "Lenovo Legion Y740-17.webp",
        liked: false,
        cart: 0,
        description: [
            'Screen Size: 1920x1080',
            'Videcard type: discrete and built-in',
            'Videocards: NVIDIA GeForce RTx 2080 MAx-Q',
            'drive configuration: SSD',
            'operation system:Windows 10 Home',
            'Type: gaming laptop',
            'Screen: 17.3" (1920x1080)',
            'Matrix: IPS, 144 Gh',
            'processor: Intel Core i7 8750H (6x2200 MGh)',
            'RAM: 16 GB DDR4 2666 MGh',
            'storage device: SSD 512 GB',
            'Size: 412x305x25.45 MM',
            'Weight: 2.9 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "OPPO A5 4/32GB",
        price: 245,
        image: "Oppo A5.png",
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.2" (1520x720)',
            'RAM: 4 GB',
            'Storage: 32 GB, with SD card slot',
            'double Cameras: 13 MP, 2 MP',
            'Battery: 4230 MA·h',
            'processor: Qualcomm Snapdragon 450',
            'SIM - cards: 2(nano SIM)',
            'operation system: Android 8.1',
            'wireless display: Wi - Fi, Bluetooth 4.2',
            'Internet: 4G LTE',
            'Weight: 170 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo ThinkPad x1 Extreme",
        price: 1670,
        image: "Lenovo ThinkPad x1 Extreme.webp",
        liked: false,
        cart: 0,
        description: [
            'operation system: Windows 10 Pro',
            'processor: Intel Core i7 9750H',
            'processor frequency: 2600 MGh',
            'processor core: Coffee Lake',
            'number of cores: 6',
            'diagonal Screena: 15.6" ',
            'Screen Size: 3840x2160',
            'widescreen Screen: available',
            'Screen Matrix Type: IPS',
            'LED backlight: available',
            'Videcard type: discrete and built-in',
            'video processor performance: NVIDIA',
            'Videocards: NVIDIA GeForce GTx 1650',
            'Videotype memory: GDDR5 '
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo IdeaPad Slim 7",
        price: 919,
        image: 'Lenovo IdeaPad Slim 7.webp',
        liked: false,
        cart: 0,
        description: [
            'processor: Intel Core i7 1065G7 1300 MGh',
            'processor core: Ice Lake',
            'number of cores: 4',
            'Cache volume L3: 8 MB',
            'microsproseccor: Intel SoC',
            'Screen : 14 inchs, 3840x2160, widescreen',
            'Screen type: glycylon',
            'Screen Matrix Type: IPS',
            'screen backlight: LED',
            'Videcard type: External',
            'Videoprocessor: Intel Iris Plus Graphics',
            'Videotype memory: SMA',
            'Web-Cameras: available, 0.92 MP',
            'Characteristics: metal case',
            'Size: 320.6x208.18x14.9 MM',
            'Weight: 1.54 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "Sony OLED KD-55A8",
        price: 1867,
        image: 'Sony OLED Sony KD-55A8.png',
        liked: false,
        cart: 0,
        description: [
            'resolution: 4K UHD (3840x2160), HDR',
            'diagonal Screena: 54.6"',
            'screen refresh rate: 50 Gh',
            'HDR format: HDR10, Dolby Vision',
            'Sound power: 30 Wt (2x10 + 2x5 Wt)',
            'Smart TV platform: Android',
            'wireless display: Wi-Fi 802.11ac, 802.11b, 802.11g, 802.11n, Bluetooth',
            'wired interfaces: HDMI 2.1 x 4, USB x 3, Ethernet, optical audio output, headphones output',
            'fortification VESA: 300x300 MM',
            'size without stand (WxHxL): 1227x712x52 MM',
            'Size with stand (WxHxL): 1227x733x326 MM',
            'Weight: 18.6 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "xiaomi Poco x3 Pro 8/256GB",
        price: 320,
        image: 'xiaomi Poco x3 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.67" (2400x1080) 120 Gh',
            'RAM: 8 GB',
            'Storage: 256 GB, 2 slots for sd card',
            '4 Cameras: 48 MP, 8 MP, 2 MP, 2 MP',
            'Battery: 5160 MA·h',
            'processor: Qualcomm Snapdragon 860',
            'SIM-cards: 2 (nano SIM)',
            'operation system: Android 11',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.0',
            'Internet: 4G LTE',
            'Security level: IP53',
            'Weight: 215 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "Oppo Reno 4 Pro 5G 256GB 12GB",
        price: 505,
        image: 'OPPO Reno 4 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.5" (2400x1080)',
            'RAM: 12 GB',
            'Storage: 256 GB',
            '3 Cameras: 48 MP, 12 MP, 13 MP',
            'Battery: 4000 MA·h',
            'processor: Qualcomm Snapdragon 765G 5G',
            'SIM-cards: 2 (nano SIM)',
            'operation system: Android 10',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.1',
            'Internet: 4G LTE',
            'Weight: 172 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Iphone 11",
        price: 895,
        image: 'Iphone 11.png',
        liked: false,
        cart: 0,
        description: [
            'OC version at the beginning of sales: iOS 13',
            'Corpus Type: Classic',
            'corpus type: Metalic and glass',
            'Construction: waterproof',
            'Security level: IP68',
            'number of SIM-cards: 2',
            'Type SIM-cards: nano SIM+eSIM',
            'contactless payment: available',
            'main (rear) Cameras: 12 MP 2x F/2.40, 12 MP F/1.80',
            'Functional main (rear) camera: autofocus, optical balanced, macro mode, optical Zoom 2x',
            'Flashlight: rear, LED',
            'video recording: available (HEVC, H.264)',
            'Max. resolution Video: 3840x2160',
            'Geo Tagging: available',
            'frontal Cameras: available, 12 MP',
            'Weight: 194 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy Tab S7 plus",
        price: 825,
        image: 'Galaxy Tab S7+.png',
        liked: false,
        cart: 0,
        description: [
            'operation system at the sales: Android 10',
            'processor: Qualcomm Snapdragon 865+ 3100 MGh',
            'processor frequency: 3100 MGh',
            'number of cores: 8',
            'processor: Kryo',
            'Techprocess: 7 nM',
            'External storage: 128 GB',
            'RAM: 6 GB LPDDR4',
            'SD card slots: available, microSDxC, up to 1024 GB',
            'Screen: 12.4", 2800x1752',
            'Screen Type: Super AMOLED, glycylon',
            'Screen sensor: capacity, multitouch',
            'number of pixels in  inches (PPI): 266',
            'Videoprocessor: Adreno 650',
            'number of main (rear) cameras:2',
            'Reslution of main (rear) cameras: 13 MP, 5 MP',
            'Characteristics Cameras: flashlight, autofocus',
            'frontal Cameras: available, 8 MP',
            'Size: 285x185x5.7 MM',
            'Weight: 575 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Elite Dragonfly G2 PC",
        price: 1959,
        image: 'HP Elite Dragonfly G2 Notebook PC.png',
        liked: false,
        cart: 0,
        description: [
            'Screen: 13.3" (3840x2160)',
            'Matrix: IPS, 60 Gh',
            'processor: Intel Core i7 1165G7 (4x2800 MGh)',
            'RAM: 32 GB LPDDR4x 4266 MGh',
            'storage device: SSD 1 ТБ',
            'external Videocards: Intel Iris xe Graphics',
            'connector: USB 3.1 Type A, HDMI output, Microphones/headphones Combo, Thunderbolt/USB 4 x 2',
            'functional USB Type-C: Thunderbolt 4',
            'Wireless connection: Wi-Fi 802.11ax, Bluetooth 5.0',
            'power capacity: 56 Wt⋅h',
            'operation system: Windows 10 Pro',
            'Size: 304.3x197.5x16.1 MM',
            'Weight: 0.99 kg'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 6,
        name: "xperia 1 II - 6.5” 4K HDR",
        price: 1959,
        image: 'xperia 1 II - 6.5” 4K HDR.png',
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.5" (3840x1644)',
            'RAM: 6 GB',
            'Storage: 128 GB, with SD card slot',
            '3 Cameras: 12 MP, 12 MP, 12 MP',
            'Battery: 3330 MA·h',
            'processor: Qualcomm Snapdragon 855',
            'SIM-cards: 2 (nano SIM)',
            'operation system: Android 9.0',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.0',
            'Internet: 4G LT',
            'main (rear) Cameras: 12 MP 2x F/1.60, 12 MP F/2.40, 12 MP F/2.40',
            'frontal Cameras: available, 8 MP',
            'number of pixels in  inches (PPI): 643'

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus Zenfone 8",
        price: 785,
        image: 'Asus Zenfone 8.png',
        liked: false,
        cart: 0,
        description: [
            'OC version at the beginning of sales: Android 11',
            'Corpus Type: Classic',
            'Construction: waterproof',
            'Security level: IP68',
            'number of SIM-cards: 2',
            'Type SIM-cards: nano SIM',
            'Screen Type: colorful AMOLED, sensor',
            'Size: 68.5x148x8.9 MM',
            'diagonal: 5.9 inches.',
            'image size: 2400x1080',
            'number of pixels in  inches (PPI): 446',
            'aspect ratio: 20:9',
            'processor: Qualcomm Snapdragon 888, 2840 MGh',
            'number of cores: 8',
            'Videoprocessor: Adreno 660',
            'built-in memory: 256 GB',
            'RAM: 16 GB',
            'Weight: 169 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "MS Surface Pro x",
        price: 1170,
        image: 'MS Surface Pro x.webp',
        liked: false,
        cart: 0,
        description: [
            'diagonal: 13" (2880x1920)',
            'externalStorage: 128 GB',
            'RAM: 8 GB',
            'processor: Microsoft SQ1',
            'operation system: Windows 10',
            'Cameras: main 10 MP, frontal 5 MP',
            'SIM-cards: 1 (nano SIM)',
            'dynamics: stereo',
            'wireless display: 4G LTE, WiFi 802.11ac, Bluetooth 5.0',
            'wired interfaces: USB-C',
            'work time: 13 h',
            'Size: 287x208x7.3 MM, Weight: 774 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Lenovo ThinkPad x1 Carbon Gen 9",
        price: 1959,
        image: 'ThinkPad x1 Carbon Gen 9.webp',
        liked: false,
        cart: 0,
        description: [
            'Screen size: 14"-14.9"',
            'operation system: Windows 10 Pro',
            'Screen Size: 1920x1080',
            'Screen sensor: Yes',
            'processor line: Intel Core i5, Intel Core i7',
            'network cards:: WLAN/Modem',
            'Wireless connection: Wi-Fi IEEE 802.11ax, Bluetooth 5.0',
            'Display: USB 3.1 Type A x 2, HDMI output, Thunderbolt 3 x 2, Microphones/headphones Combo',
            'functional USB Type-C: Thunderbolt 3',
            'Web-Cameras: available, 0.92 MP',
            'fingerprint availability: available',
            'Characteristics: metal case, security lock slot',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "OPPO A94",
        price: 757,
        image: 'OPPO A94.png',
        liked: false,
        cart: 0,
        description: [
            'Screen: 6.43" (2400x1080) 60 Gh',
            'RAM: 4 GB',
            'Storage: 128 GB, with SD card slot',
            '3 Cameras: 48 MP, 2 MP, 2 MP',
            'Battery: 5000 MA·h',
            'processor: Qualcomm Snapdragon 662',
            'SIM-cards: 2 (nano SIM)',
            'operation system: Android 11',
            'wireless display: NFC, Wi-Fi, Bluetooth 5.0',
            'Internet: 4G LTE',
            'Weight: 175 g'
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus ZenBook-15-Ux533",
        price: 1336,
        image: 'Asus ZenBook-15-Ux533.png',
        liked: false,
        cart: 0,
        description: [
            'Screen size:15"-15.9"',
            'Screen Size:1920x1080',
            'Screen sensor: not available',
            'processor line:Intel Core i5',
            'MODEL 90NB0NK5-M05600',
            'Screen: 15.6 inchs, 1920x1080, widescreen',
            'operation system: Windows 10 Home',
            'Screen type: frost',
            'Screen Matrix Type: IPS',
            'screen refresh rate: 60 Gh',
            'screen backlight: LED',
            'Videcard type: discrete and built-in',
            'Videoprocessor: NVIDIA GeForce GTx 1650 MAx-Q',
            'video memory size: 4 GB',
            'Videotype memory: GDDR5',
            'Weight: 1.65 kg'
        ]
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 10,
        name: "Asus ROG Phone 5 Pro",
        price: 1308,
        image: 'Asus ROG Phone 5 Pro.png',
        liked: false,
        cart: 0,
        description: [
            'OC version at the beginning of sales: Android 11',
            'corpus type: aluminium and glass',
            'number of SIM-cards: 2',
            'contactless payment: available',
            'Size: 77.3x172.8x10.3 MM',
            'Screen Type: colorful AMOLED, sensor',
            'diagonal: 6.78 inches.',
            'image size: 2448x1080',
            'number of pixels in  inches (PPI): 395',
            'processor: Qualcomm Snapdragon 888',
            'number of cores: 8',
            'Videoprocessor: Adreno 660',
            'built-in memory: 256 GB',
            'RAM: 16 GB',
            'number of main (rear) cameras: 3',
            'main (rear) Cameras: wide angle 64 MP F/1.80, superangular 13 MP F/2.40, Macro 5 MP F/2',
            'Функции основной (rear) PhotoCameras: autofocus, optical balanced',
            'flashlight: rear',
            'Weight: 238 g'
        ]
    }
]

export { brands, products }